// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying the MCP connection.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-systems.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_systems_default = defineTool2({
  name: "list_systems",
  title: "List systems",
  description: "List the built-in systems (schedules, audits, supervision) available in the app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const systems = [
      { path: "/teacher", title: "\u062C\u062F\u0648\u0644 \u0627\u0644\u062A\u062F\u0631\u064A\u0633\u064A\u064A\u0646" },
      { path: "/student", title: "\u062C\u062F\u0648\u0644 \u0627\u0644\u0637\u0644\u0628\u0629" },
      { path: "/audit", title: "\u0623\u0646\u0638\u0645\u0629 \u0627\u0644\u062A\u062F\u0642\u064A\u0642" },
      { path: "/tracking", title: "\u0645\u062A\u0627\u0628\u0639\u0629 \u0627\u0644\u062A\u062F\u0631\u064A\u0633" },
      { path: "/empty-rooms", title: "\u0627\u0644\u0642\u0627\u0639\u0627\u062A \u0627\u0644\u0641\u0627\u0631\u063A\u0629" },
      { path: "/assignments", title: "\u0627\u0644\u062A\u0643\u0644\u064A\u0641\u0627\u062A" },
      { path: "/individual-assignments", title: "\u0627\u0644\u062A\u0643\u0644\u064A\u0641\u0627\u062A \u0627\u0644\u0641\u0631\u062F\u064A\u0629" },
      { path: "/supervision-report", title: "\u062A\u0642\u0631\u064A\u0631 \u0627\u0644\u0625\u0634\u0631\u0627\u0641" },
      { path: "/projects", title: "\u0627\u0644\u0645\u0634\u0627\u0631\u064A\u0639" },
      { path: "/charts", title: "\u0627\u0644\u0625\u062D\u0635\u0627\u0626\u064A\u0627\u062A" }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(systems, null, 2) }],
      structuredContent: { systems }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "civil-academi-mcp",
  title: "Civil Academi MCP",
  version: "0.1.0",
  instructions: "\u0623\u062F\u0648\u0627\u062A \u0643\u0644\u064A\u0629 \u0627\u0644\u0647\u0646\u062F\u0633\u0629 \u0627\u0644\u0645\u062F\u0646\u064A\u0629: \u0627\u0633\u062A\u062E\u062F\u0645 `echo` \u0644\u0644\u062A\u062D\u0642\u0642 \u0645\u0646 \u0627\u0644\u0627\u062A\u0635\u0627\u0644\u060C \u0648`list_systems` \u0644\u0645\u0639\u0631\u0641\u0629 \u0627\u0644\u0623\u0646\u0638\u0645\u0629 \u0627\u0644\u0645\u062A\u0627\u062D\u0629.",
  tools: [echo_default, list_systems_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
